# Generated by Django 4.0.6 on 2022-07-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataIngest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CassiniData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('duration', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('team', models.CharField(max_length=25)),
                ('spass_type', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=25)),
                ('request_name', models.CharField(max_length=50)),
                ('library_definition', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('identifier', models.UUIDField()),
            ],
            options={
                'db_table': 'cassinni_data',
            },
        ),
    ]
