# Generated by Django 4.0.6 on 2022-07-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataIngest', '0002_cassinidata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassinidata',
            name='identifier',
            field=models.UUIDField(unique=True),
        ),
    ]
