# Generated by Django 4.0.6 on 2022-07-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataIngest', '0003_alter_cassinidata_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassinidata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cassinidata',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cassinidata',
            name='duration',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cassinidata',
            name='library_definition',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cassinidata',
            name='request_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cassinidata',
            name='spass_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cassinidata',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cassinidata',
            name='target',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cassinidata',
            name='team',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cassinidata',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
