# Generated by Django 4.0.6 on 2022-07-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataIngest', '0004_alter_cassinidata_date_alter_cassinidata_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cassinidata',
            old_name='start_time',
            new_name='start_time_utc',
        ),
    ]
