# Generated by Django 4.0.6 on 2022-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataIngest', '0005_rename_start_time_cassinidata_start_time_utc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassinidata',
            name='start_time_utc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
