# Generated by Django 4.0.6 on 2022-07-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataIngest', '0006_alter_cassinidata_start_time_utc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassinidata',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
